/**
 * @jest-environment jsdom
 */

import { script } from '@/components/ui/gluestack-ui-provider/script';

// jsdom provides no `TextEncoder`, and Expo installs a *lazy* global `URL` getter backed by
// `whatwg-url-minimum`, which needs one. `src/api/client.ts` calls `new URL(baseUrl)` at module
// load, and `jest.setup.ts`'s global store reset pulls that in — so without these two the very
// first `beforeEach` fails with "TextEncoder is not defined" before any assertion runs.
// `require`d rather than imported because `tsconfig.json`'s `types` does not include node, and
// that file is regenerated by `npx expo customize tsconfig.json` in CI.
Object.assign(globalThis, {
  TextEncoder: require('node:util').TextEncoder,
  TextDecoder: require('node:util').TextDecoder,
});

/**
 * This is the only file in the repo that needs a DOM. jest-expo's default environment is
 * React Native's, which has no `document` and no `matchMedia`, so the environment is
 * overridden per-file rather than by splitting Jest into projects for one module.
 *
 * `script` is stringified into a `<script>` tag by the web provider and runs before hydration
 * to set the colour-mode class. It is never called from React, which is why it is tested
 * directly.
 */

function setSystemPrefersDark(matches: boolean) {
  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    value: jest.fn().mockReturnValue({ matches }),
  });
}

beforeEach(() => {
  document.documentElement.className = '';
  document.documentElement.style.colorScheme = '';
  setSystemPrefersDark(false);
});

describe('script', () => {
  it('applies an explicit mode without consulting the system', () => {
    setSystemPrefersDark(true);

    script('light');

    expect(document.documentElement.classList.contains('light')).toBe(true);
    expect(document.documentElement.classList.contains('dark')).toBe(false);
    expect(document.documentElement.style.colorScheme).toBe('light');
    expect(window.matchMedia).not.toHaveBeenCalled();
  });

  it('applies dark when asked for dark', () => {
    script('dark');

    expect(document.documentElement.classList.contains('dark')).toBe(true);
    expect(document.documentElement.style.colorScheme).toBe('dark');
  });

  it('follows the system preference when the mode is "system"', () => {
    setSystemPrefersDark(true);

    script('system');

    expect(window.matchMedia).toHaveBeenCalledWith('(prefers-color-scheme: dark)');
    expect(document.documentElement.classList.contains('dark')).toBe(true);
  });

  it('falls back to light when the system prefers light', () => {
    setSystemPrefersDark(false);

    script('system');

    expect(document.documentElement.classList.contains('light')).toBe(true);
  });

  it('removes the opposite class, so switching modes does not leave both applied', () => {
    script('dark');
    script('light');

    expect(document.documentElement.classList.contains('light')).toBe(true);
    expect(document.documentElement.classList.contains('dark')).toBe(false);
  });

  // This runs in a shipped web build, and the page renders correctly on the dark default
  // without the colour-scheme class — so it warns in development and says nothing in
  // production, rather than putting a DOM exception in a user's console.
  it('swallows a DOM failure rather than throwing, and does not console.error', () => {
    const consoleError = jest.spyOn(console, 'error').mockImplementation(() => {});
    const consoleWarn = jest.spyOn(console, 'warn').mockImplementation(() => {});
    // `system` reaches for matchMedia; making it throw exercises the catch without having to
    // break documentElement itself.
    Object.defineProperty(window, 'matchMedia', {
      writable: true,
      value: () => {
        throw new Error('matchMedia unavailable');
      },
    });

    expect(() => script('system')).not.toThrow();
    expect(consoleError).not.toHaveBeenCalled();
    // `__DEV__` is true under the preset, so the development arm is what runs here.
    expect(consoleWarn).toHaveBeenCalled();

    consoleError.mockRestore();
    consoleWarn.mockRestore();
  });
});
